### PR TITLE
fixing to support block assignment of hash

### PR DESCRIPTION
**Pull request by pbrumm**

### CODE REVIEW

**Comment by bararchy** [comment]
:ok: looks good :) btw @pbrumm are you using the shard? do you find it useful?

**Comment by pbrumm** [comment]
just getting started with it after spending a lot of time tracing down an inconsistent hash corruption bug.   

looks useful.    after digging into the crystal code there could be some meta programming to only add the semaphore if preview_mt is set.

Thanks for developing this.

**Comment by bararchy** [comment]
@pbrumm Glad you like it! I would maybe suggest, we at @NeuraLegion have moved to use  https://github.com/NeuraLegion/generic_actor to safe-guard against MT issues, take a look you might find it userful! it uses an actor model with Channels and Fibers instead of a lock

**Comment by pbrumm** [comment]
interesting.    I will take a look.

**Pull request merged**
